In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [4]:
list = [3,4,5,1.1,"Krunalsinh"]
list

[3, 4, 5, 1.1, 'Krunalsinh']

In [6]:
np.array(list)

array(['3', '4', '5', '1.1', 'Krunalsinh'], dtype='<U32')

In [7]:
list2 = [[1,2,3,4], [4,7,2,6], [8,5,7,3]]
list2

[[1, 2, 3, 4], [4, 7, 2, 6], [8, 5, 7, 3]]

In [8]:
np.array(list2)

array([[1, 2, 3, 4],
       [4, 7, 2, 6],
       [8, 5, 7, 3]])

In [10]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr = np.arange(0,15,2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [12]:
arr = np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [14]:
arr = np.zeros((3,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
arr = np.ones(3)
arr

array([1., 1., 1.])

In [16]:
arr = np.ones((3,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
arr = np.linspace(1,10,9)
arr

array([ 1.   ,  2.125,  3.25 ,  4.375,  5.5  ,  6.625,  7.75 ,  8.875,
       10.   ])

In [21]:
np.random.rand(10)

array([0.4734623 , 0.80046688, 0.11576897, 0.20863244, 0.79958856,
       0.59131194, 0.77834733, 0.61990315, 0.86114809, 0.58292269])

In [30]:
np.random.randn(10)

array([-0.06796487,  0.7425937 , -1.27457686, -1.32459487,  0.00970444,
        0.70198481,  0.50020662,  0.57177307, -0.57506387,  2.29899167])

In [32]:
np.random.randint(5,50,10)

array([ 5, 45,  7, 26, 19,  6, 21,  8, 39, 48], dtype=int32)

Array Attribute

In [34]:
arr = np.array([[1,2,3,4], [4,7,2,6], [8,5,7,3]])
arr

array([[1, 2, 3, 4],
       [4, 7, 2, 6],
       [8, 5, 7, 3]])

In [35]:
arr.shape

(3, 4)

In [36]:
arr.size

12

In [37]:
arr.dtype

dtype('int64')

Array Methods

In [38]:
arr

array([[1, 2, 3, 4],
       [4, 7, 2, 6],
       [8, 5, 7, 3]])

In [39]:
arr.min()

np.int64(1)

In [40]:
arr.max()

np.int64(8)

In [41]:
arr.sum()

np.int64(52)

In [42]:
np.sum(arr, axis=0)

array([13, 14, 12, 13])

In [44]:
np.sum(arr, axis=1)

array([10, 19, 23])

In [45]:
arr.mean()

np.float64(4.333333333333333)

In [46]:
arr.std()

np.float64(2.173067468400883)

In [47]:
arr.argmax()

np.int64(8)

In [48]:
arr.argmin()

np.int64(0)

Reshaping and Resizing

In [51]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [52]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [53]:
arr = arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])