In [1]:
import numpy as np

NUMPY INDEXING AND SLICING OF VECTOR

In [2]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [10]:
arr_index = arr[5]
arr_index

np.int64(16)

In [11]:
arr_slice = arr[3:9]
arr_slice

array([14, 15, 16, 17, 18, 19])

In [12]:
arr_slice1 = arr[:7]
arr_slice1

array([11, 12, 13, 14, 15, 16, 17])

In [13]:
arr_slice2 = arr[3:]
arr_slice2

array([14, 15, 16, 17, 18, 19, 20])

In [14]:
arr_slice3 = arr[2:9:2]
arr_slice3

array([13, 15, 17, 19])

NUMPY INDEXING AND SLICING OF MATRIX

In [15]:
arr = np.arange(1,31).reshape(5,6)
arr                              

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [30]:
arr_index = arr[3,5]
arr_index

np.int64(24)

In [33]:
slice = arr[2:5,4:6]
slice

array([[17, 18],
       [23, 24],
       [29, 30]])

In [35]:
arr[:,3]

array([ 4, 10, 16, 22, 28])

BOOLEAN INDEXING

In [36]:
arr = np.arange(11,31)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30])

In [37]:
bool_index = arr % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True])

In [38]:
arr1 = arr[bool_index]
arr1

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30])