In [1]:
import numpy as np

ARRAY OPERATIONS

Arithmetic operations

In [3]:
arr1 = np.array([4,32,6,7,3,8])
arr2 = np.array([9,5,2,4,23,1])

In [4]:
arr1 + arr2

array([13, 37,  8, 11, 26,  9])

In [5]:
arr1 - arr2

array([ -5,  27,   4,   3, -20,   7])

In [6]:
arr1 * arr2

array([ 36, 160,  12,  28,  69,   8])

In [7]:
arr1 / arr2

array([0.44444444, 6.4       , 3.        , 1.75      , 0.13043478,
       8.        ])

In [8]:
arr1 // arr2

array([0, 6, 3, 1, 0, 8])

In [9]:
arr1 % arr2

array([4, 2, 0, 3, 3, 0])

In [10]:
arr1 ** arr2 

array([     262144,    33554432,          36,        2401, 94143178827,
                 8])

In [19]:
arr3 * 2

array([[12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50],
       [52, 54, 56, 58, 60]])

Broadcasting

In [12]:
l = [10,20,30,40,50]
arr = np.array(l)

In [14]:
arr+10

array([20, 30, 40, 50, 60])

In [16]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [18]:
arr3 = arr2 + 5
arr3

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

Deep and Shallow copy

In [30]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [31]:
slice = a[:6]
slice * 10

array([10, 20, 30, 40, 50, 60])

In [32]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [36]:
b = a.copy()
b = b*10

In [37]:
b

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150, 160, 170, 180, 190, 200])

In [38]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

Matrix operations

In [41]:
a = np.array([[4,7],[6,2]])
b = np.array([[9,1],[5,3]])

In [42]:
a * b

array([[36,  7],
       [30,  6]])

In [43]:
a @ b

array([[71, 25],
       [64, 12]])

In [44]:
np.dot(a,b)

array([[71, 25],
       [64, 12]])

In [45]:
a.T

array([[4, 6],
       [7, 2]])

Advance Array Manipulation

Stacking Array

In [49]:
a = np.array([1,4,6,8])
b = np.array([2,6,1,9])

In [50]:
np.vstack((a,b))

array([[1, 4, 6, 8],
       [2, 6, 1, 9]])

In [51]:
np.hstack((a,b))

array([1, 4, 6, 8, 2, 6, 1, 9])

In [52]:
np.column_stack((a,b))

array([[1, 2],
       [4, 6],
       [6, 1],
       [8, 9]])

Splitting array

In [53]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [55]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [56]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [57]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [58]:
np.vsplit(c,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]